entries:
  - client/index.js:assets/index.js
  - client/index.css:assets/index.css
geocoder:
  focus:
    lat: 38.887090
    lon: -77.095229
    radius: 100
s3bucket: commute-staging
modeshareStats:
  carpool: 0.10
  bike: 0.02
  transit: 0.14
